Check that layers array items are objects (#1026)
* Fix unhandled error when layers contains primitive

Fixes an unhandled error occurring when a non-object type value is used
as a layer item, e.g. `layers: [123]`.

For primitive types, this caused an error such as:

> TypeError: Cannot use 'in' operator to search for 'ref' in 123

For `null` values, this caused an error such as:

> TypeError: Cannot read properties of null (reading 'type')

* Update CHANGELOG